#!/usr/bin/env bash
#
# Shared systemd-unit helpers.
#
# A systemd unit is NOT a shell script, but it is generated by one. Two failure
# modes follow, and both are silent:
#
#   1. Directive injection. A newline inside any interpolated value starts a new
#      directive. A value such as
#          /opt/xistance\nExecStart=/bin/sh -c '...'
#      replaces the service command entirely.
#   2. Argument splitting. ExecStart is split on whitespace unless each argument
#      is quoted, so a release path containing a space runs the wrong file.
#
# Everything the installers interpolate into a unit goes through these helpers.

# Reject a value that could inject a directive or break quoting.
#
# A newline, carriage return, or NUL is never legitimate in a path or a
# description. Control characters are stripped rather than merely rejected so a
# stray tab or trailing space cannot reintroduce the problem.
#
# Usage: xt_unit_safe <label> <value>
# Prints the sanitised value on success, or returns 1 with a reason.
xt_unit_safe() {
  local label="${1:-value}" value="${2-}"

  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    printf 'refusing to write a %s containing a newline into a systemd unit\n' \
      "$label" >&2
    return 1
  fi

  # Strip remaining control characters, which systemd would read as separators.
  # This cannot remove a newline because that was rejected above.
  value="${value//[$'\001'-$'\010'$'\013'$'\014'$'\016'-$'\037']/}"

  # An empty value would silently produce a broken directive.
  if [[ -z "$value" ]]; then
    printf 'refusing to write an empty %s into a systemd unit\n' "$label" >&2
    return 1
  fi

  printf '%s' "$value"
}

# Escape a value for use inside a double-quoted systemd directive.
#
# systemd honours C-style escapes inside double quotes, so a literal backslash
# or double quote in the value must be escaped. A value containing a single
# quote is safe as-is inside double quotes.
#
# Usage: xt_unit_quote <value>
xt_unit_quote() {
  local value="${1-}"
  value="${value//\\/\\\\}"   # backslash first, or the escapes below get doubled
  value="${value//\"/\\\"}"   # then the quote
  printf '"%s"' "$value"
}

# Render the panel's systemd unit to stdout.
#
# Every value is sanitised and quoted, so the result is safe to write for any
# input the installers can produce. On refusal it returns non-zero and prints
# nothing, so a caller cannot accidentally write a partial unit.
#
# Usage: xt_render_service_unit <env_file> <release_root> <node_bin> <user> [description]
xt_render_service_unit() {
  local env_file="${1:-}" release_root="${2:-}" node_bin="${3:-}" user="${4:-}"
  local description="${5:-Xistance Tunnel Control Panel}"
  local safe_env safe_root safe_node safe_user safe_desc server_js

  safe_env="$(xt_unit_safe "environment file" "$env_file")" || return 1
  safe_root="$(xt_unit_safe "release root" "$release_root")" || return 1
  safe_node="$(xt_unit_safe "node binary" "$node_bin")" || return 1
  safe_user="$(xt_unit_safe "service user" "$user")" || return 1
  safe_desc="$(xt_unit_safe "description" "$description")" || return 1

  # The server is a fixed suffix on an already-validated root.
  server_js="${safe_root}/apps/web/server.js"

  # IMPORTANT: EnvironmentFile and WorkingDirectory take the path *unquoted*.
  # systemd does not strip quotes in those directives, so a quoted value fails
  # with "path is not absolute" and the unit is rejected as fatally broken --
  # while a previously started process keeps answering on the port and makes
  # the failure look like a successful install. Only ExecStart is an argv list
  # and therefore the only one that takes quotes.
  cat <<EOF
[Unit]
Description=${safe_desc}
Documentation=https://github.com/insekt1024/xistance-panel
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${safe_env}
# WorkingDirectory and ExecStart resolve through the active release pointer, so
# an atomic cutover is picked up by the next service start.
WorkingDirectory=${safe_root}
ExecStart=$(xt_unit_quote "$safe_node") $(xt_unit_quote "$server_js")
Restart=on-failure
RestartSec=5
User=${safe_user}
Group=${safe_user}
RuntimeDirectory=xistance
RuntimeDirectoryMode=0750
# The panel serves a web UI and spawns tunnel binaries; it does not need to
# write the system, so the filesystem is kept read-only apart from its state
# directories.
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictSUIDSGID=true
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
}

# Write the unit and surface every service-control failure.
#
# Writing the unit is not enough: systemd will happily keep serving the old
# unit until it is reloaded, so a silent failure here looks like a successful
# install while the new release never starts. Each step is therefore checked.
#
# Usage: xt_install_service <unit_content_file> <unit_path> [service_name]
xt_install_service() {
  local source_file="$1" unit_path="$2" service="${3:-xistance.service}"

  if ! command -v systemctl >/dev/null 2>&1; then
    printf 'systemd (systemctl) is not available on this host.\n' >&2
    return 1
  fi

  local unit_dir
  unit_dir="$(dirname "$unit_path")"
  if [[ ! -d "$unit_dir" ]]; then
    printf 'systemd unit directory %s does not exist.\n' "$unit_dir" >&2
    return 1
  fi

  if ! install -m 0644 "$source_file" "$unit_path"; then
    printf 'could not write %s\n' "$unit_path" >&2
    return 1
  fi

  # daemon-reload failing means systemd is not managing units here; continuing
  # would report a success that never takes effect.
  if ! systemctl daemon-reload; then
    printf 'systemctl daemon-reload failed; systemd did not accept the new unit.\n' >&2
    return 1
  fi

  if ! systemctl enable "$service" >/dev/null 2>&1; then
    printf 'could not enable %s (it will not start on boot).\n' "$service" >&2
    return 1
  fi

  return 0
}
