#!/bin/bash
# =============================================================================
# Real-binary traffic for the methods whose configs the PANEL builds.
#
# Why this exists (TASK-126): 7 of 8 traffic claims in real-binary-evidence.json
# rested on probes that lived in /tmp on containers that no longer exist, and no
# test in the repo started a binary and moved a byte for them. This is that test.
#
# Every config in $FX is generated by scripts/gen-traffic-fixtures.ts from the
# PRODUCT'S OWN builders, with each input parsed through the real Zod schema first.
# Nothing here is hand-written, so a regression in a builder fails here instead of
# passing silently. (A hand-written replica proves the replica -- TASK-124 burned
# five attempts on exactly that for XRAY.)
#
# Assert the PRECONDITION before measuring: if the origin is not serving, every
# later failure is misattributed to the tunnel under test. That rule came from
# TASK-124, where three XRAY assertions failed for an unrelated reason.
#
# Runs on the target OS (Ubuntu 24.04.5, systemd as PID 1), against binaries in
# $XT_BIN_DIR installed by scripts/install.sh with pinned digests.
#
# Usage: bash test-real-traffic-target-os.sh <fixture-dir> [bin-dir]
# Exit 0 only when every method carries real bytes.
# =============================================================================
set -uo pipefail
# Invoked with no arguments (by run-all-tests.ts on a dev host, where there is no
# target container) this SKIPS loudly rather than erroring. An error here would read
# as a product failure; a skip states plainly that no evidence was gathered.
if [ "$#" -lt 1 ]; then
  echo "  SKIP real-binary traffic: needs <fixture-dir> [bin-dir]; run it inside a target-OS container"
  echo "       (the adapter scripts/test-real-traffic-target-os.ts runs this for you)"
  echo "RESULT: pass=0 fail=0 skipped=1"
  exit 0
fi
FX="$1"
BIN="${2:-${XT_BIN_DIR:-/var/lib/xistance/bin}}"
ORIGIN_PORT=19098
pass=0; fail=0
ok(){ echo "  ok   $1"; pass=$((pass+1)); }
bad(){ echo "  FAIL $1"; echo "       $2"; fail=$((fail+1)); }

# Binaries are a PRECONDITION too: without them every probe below fails for a
# reason that has nothing to do with the product.
missing=""
for b in backhaul frpc frps gost; do
  [ -x "$BIN/$b" ] || missing="$missing $b"
done
if [ -n "$missing" ]; then
  echo "  FAIL PRECONDITION: binaries present in $BIN" "missing:$missing"
  echo "RESULT: pass=$pass fail=$((fail+1))"
  exit 1
fi
ok "PRECONDITION: backhaul, frpc, frps and gost are present in $BIN"

# Refuse to start if a previous run is still holding fixture ports. Two overlapping
# runs make every method fail at once, which reads as "the product is broken" when it
# is only contention -- the worst possible thing a gate can report.
for port in 18100 18101 18102 18103 18104 18105 18106 19098 19083; do
  if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
    exec 3>&- 2>/dev/null
    echo "  FAIL PRECONDITION: no other run holds the fixture ports" \
         "127.0.0.1:${port} is already accepting connections; another suite run is still active"
    echo "RESULT: pass=0 fail=1"
    exit 1
  fi
done
ok "PRECONDITION: no other run holds the fixture ports"

# ---------------------------------------------------------------- origin -----
cat > /tmp/o.py <<'PY'
import http.server, socketserver
class H(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        b = b"HELLO-XR"
        self.send_response(200)
        self.send_header("Content-Length", str(len(b)))
        self.end_headers()
        self.wfile.write(b)
    def log_message(self, *a): pass
socketserver.TCPServer.allow_reuse_address = True
socketserver.TCPServer(("127.0.0.1", 19098), H).serve_forever()
PY
printf "[Unit]\nDescription=origin under test\n[Service]\nExecStart=/usr/bin/python3 /tmp/o.py\nRestart=always\nRestartSec=1\n" > /etc/systemd/system/ot.service
systemctl daemon-reload; systemctl stop ot 2>/dev/null; systemctl start ot
body(){ curl -s --max-time 6 "http://127.0.0.1:$1" 2>/dev/null; }
for i in $(seq 1 15); do [ "$(body 19098)" = "HELLO-XR" ] && break; sleep 1; done
if [ "$(body 19098)" != "HELLO-XR" ]; then
  bad "PRECONDITION: the origin answers" "19098 returned '$(body 19098)' -- no tunnel result below would be meaningful"
  echo "RESULT: pass=$pass fail=$fail"; exit 1
fi
ok "PRECONDITION: the origin answers HELLO-XR on 19098"

# ------------------------------------------------------------------ GOST -----
# argv comes straight from buildGostCommand(): gost -L tcp://:<listen>/<host>:<port>
# The builders emit a JSON ARRAY. Reading it with -r turns it into separate words,
# so argv[0] is the binary and the rest are its arguments. `eval "$BIN/$ARGV"`
# instead made bash look for a file literally named "[gost,-L,...]".
read -r -a GOST_ARGV < <(tr -d '[]"' < $FX/gost-argv.json | tr ',' ' ')
echo "  gost argv: ${GOST_ARGV[*]}"
GPORT=$(printf '%s' "${GOST_ARGV[*]}" | sed -n 's/.*:\([0-9]\+\)\/.*/\1/p')
"$BIN/${GOST_ARGV[0]}" "${GOST_ARGV[@]:1}" > /tmp/gost.log 2>&1 & GP=$!
sleep 2
gb=$(body "$GPORT")
if [ "$gb" = "HELLO-XR" ]; then ok "GOST carries real bytes through buildGostCommand() output (port $GPORT)"
else bad "GOST carries real bytes" "port $GPORT returned '$gb'; $(tail -1 /tmp/gost.log)"; fi
kill $GP 2>/dev/null

# ---------------------------------------------------------------- DIRECT -----
# DIRECT is also gost, but with an explicit bind address -- a different builder path.
read -r -a D_ARGV < <(tr -d '[]"' < $FX/direct-argv.json | tr ',' ' ')
echo "  direct argv: ${D_ARGV[*]}"
DPORT=$(printf '%s' "${D_ARGV[*]}" | sed -n 's/.*127\.0\.0\.1:\([0-9]\+\)\/.*/\1/p')
# As a unit, not a background job, so reconnect_case can SIGKILL its MainPID the
# way the panel's own supervised unit would be killed.
printf "[Unit]\nDescription=gost direct under test\n[Service]\nExecStart=$BIN/${D_ARGV[0]} ${D_ARGV[*]:1}\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/gost-direct.service
systemctl daemon-reload; systemctl stop gost-direct 2>/dev/null; systemctl start gost-direct
sleep 3
db=$(body "$DPORT")
if [ "$db" = "HELLO-XR" ]; then ok "DIRECT carries real bytes through buildDirectCommand() output (port $DPORT)"
else bad "DIRECT carries real bytes" "port $DPORT returned '$db'; $(tail -1 /tmp/direct.log)"; fi
# left running for the reconnect phase

# ------------------------------------------------------------------- FRP -----
printf "[Unit]\nDescription=frps\n[Service]\nExecStart=$BIN/frps -c $FX/frps.toml\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/frps.service
printf "[Unit]\nDescription=frpc\n[Service]\nExecStart=$BIN/frpc -c $FX/frpc.toml\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/frpc.service
systemctl daemon-reload; systemctl stop frps frpc 2>/dev/null; systemctl start frps; sleep 2; systemctl start frpc; sleep 4
fb=$(body 18100)
if [ "$fb" = "HELLO-XR" ]; then ok "FRP carries real bytes through the product's buildFrpPair output (port 18100)"
else bad "FRP carries real bytes" "18100 returned '$fb'; frps: $(journalctl -u frps --no-pager -n 2 2>/dev/null | tail -1)"; fi

# ---------------------------------------------------------------- BACKHAUL ---
printf "[Unit]\nDescription=bh-server\n[Service]\nExecStart=$BIN/backhaul -c $FX/backhaul-server.json server\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/bhs.service
printf "[Unit]\nDescription=bh-client\n[Service]\nExecStart=$BIN/backhaul -c $FX/backhaul-client.json client\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/bhc.service
systemctl daemon-reload; systemctl stop bhs bhc 2>/dev/null; systemctl start bhs; sleep 2; systemctl start bhc
# Poll rather than sleep once: the client dials the server, and on a cold pair the
# first probe lands before the tunnel is up.
bb=""
for i in $(seq 1 15); do sleep 1; bb=$(body 18101); [ -n "$bb" ] && break; done
if [ "$bb" = "HELLO-XR" ]; then ok "BACKHAUL carries real bytes through buildBackhaulConfig() output (port 18101)"
else bad "BACKHAUL carries real bytes" "18101 returned '$bb'; server: $(journalctl -u bhs --no-pager -n 2 2>/dev/null | tail -1)"; fi

# --------------------------------------------------------------- SSH/REVERSE ---
# Both argv files come from the product's own builders (buildSshCommand, and
# reverseToSshConfig -> buildSshCommand for REVERSE). They need a live sshd.
#
# SKIP rather than fail when there is none: the xt24 target image ships
# openssh-client only and has no network to install the server
#   E: Failed to fetch .../openssh-server_...deb  Temporary failure resolving
# That is an environment limit, and the argv itself is still asserted below -- a
# missing peer must not be reported as a product failure, nor as a pass.
sshd_present=0
[ -x /usr/sbin/sshd ] && sshd_present=1

# The argv IS checked either way: it is the product's output, and a regression in
# buildSshCommand or the REVERSE mapping must fail even with no sshd to run.
check_ssh_argv() {
  local name="$1" file="$2" expect="$3" port="$4"
  local argv
  if [ ! -s "$FX/$file" ]; then
    bad "$name argv is generated by the product's builder" "$FX/$file is missing"
    return
  fi
  argv=$(tr -d '[]"' < "$FX/$file" | tr ',' ' ')
  # `grep -F` for a literal, and pattern is matched against the joined argv so a
  # token like "-L" is found wherever it lands.
  if printf '%s\n' "$argv" | grep -qF -- "$expect"; then
    ok "$name argv carries the product's builder output ($expect present)"
  else
    bad "$name argv is generated by the product's builder" \
        "expected literal '$expect'; read from $FX/$file as: ${argv:-<empty>}"
  fi
  if [ "$sshd_present" -eq 0 ]; then
    echo "       SKIP $name execution: no /usr/sbin/sshd on this target and no network to install one (TASK-128)"
    return
  fi
  # A throwaway keypair generated HERE -- never a credential from the repo.
  install -d -m 700 /root/.ssh
  [ -f "$KEY" ] || ssh-keygen -q -t ed25519 -N "" -f "$KEY" </dev/null
  install -d -m 700 /root/.ssh
  cat /root/.ssh/authorized_keys 2>/dev/null > /root/.ssh/ak.bak 2>/dev/null || true
  cat "$KEY.pub" >> /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
  read -r -a A < <(tr ',' ' ' <<< "$(tr -d '[]"' < "$FX/$file")")
  # shellcheck disable=SC2086
  ssh "${A[@]:1}" > /tmp/ssh-$name.log 2>&1 & SP=$!
  sleep 4
  local got; got=""
  for i in $(seq 1 12); do got=$(body "$port"); [ -n "$got" ] && break; sleep 1; done
  if [ "$got" = "HELLO-XR" ]; then ok "$name carries real bytes through the tunnel (port $port)"
  else bad "$name carries real bytes" "port $port returned '$got'; $(tail -1 /tmp/ssh-$name.log)"; fi
  kill $SP 2>/dev/null
  mv -f /root/.ssh/ak.bak /root/.ssh/authorized_keys 2>/dev/null || true
  rm -f /root/.ssh/ak.bak
}
KEY="${KEY:-/root/.ssh/id_ed25519_traffic}"
check_ssh_argv SSH   ssh-argv.json "-L" 18104
check_ssh_argv REVERSE reverse-argv.json "-R" 18106

# -------------------------------------------------------------------- XRAY ---
# The CLIENT config is the product's buildXrayConfig() output; the server inbound is
# the 3X-UI side the panel expects an operator to provide.
#
# The inbound is `dokodemo-door` with no `address`, so traffic reaches it via an
# iptables REDIRECT and xray recovers the original destination via
# SO_ORIGINAL_DST -- which is what followRedirect:true enables (TASK-125). The
# redirect is scoped to non-xray traffic with `-m owner`, because a bare rule also
# captures the far end's own dial back into the tunnel.
XRAY_PORT=18105
if [ ! -x "$BIN/xray" ]; then
  echo "       SKIP XRAY: no xray in $BIN (run scripts/install.sh --yes on it first)"
elif [ ! -s "$FX/xray-client.json" ] || [ ! -s "$FX/xray-server.json" ]; then
  bad "XRAY configs are generated by the product's builder" "one of xray-client.json / xray-server.json is missing"
else
  # Assert the shipped setting BEFORE running, so a regression in buildXrayConfig is
  # named as such rather than showing up as a dead tunnel.
  if grep -q '"followRedirect": true' "$FX/xray-client.json"; then
    ok "XRAY client config sets followRedirect:true (the product's builder)"
  else
    bad "XRAY client config sets followRedirect:true" \
        "with followRedirect:false dokodemo-door dials its own listen port (TASK-125): $(grep -o '"followRedirect":[^,]*' "$FX/xray-client.json")"
  fi

  printf "[Unit]\nDescription=xray server under test\n[Service]\nUser=xistance\nExecStart=$BIN/xray run -c $FX/xray-server.json\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/xs.service
  printf "[Unit]\nDescription=xray client under test\n[Service]\nUser=xistance\nExecStart=$BIN/xray run -c $FX/xray-client.json\nRestart=always\nRestartSec=2\n" > /etc/systemd/system/xc.service
  systemctl daemon-reload; systemctl stop xs xc 2>/dev/null; systemctl start xs; sleep 3; systemctl start xc; sleep 4
  # Scoped so the tunnel's own outbound is not redirected back into itself.
  iptables -t nat -A OUTPUT -p tcp --dport 19098 -m owner ! --uid-owner xistance -j REDIRECT --to-port $XRAY_PORT 2>/dev/null
  xb=""
  for i in $(seq 1 15); do sleep 1; xb=$(body 19098); [ "$xb" = "HELLO-XR" ] && break; done
  if [ "$xb" = "HELLO-XR" ]; then ok "XRAY carries real bytes through the product's buildXrayConfig() output"
  else bad "XRAY carries real bytes" "origin through the tunnel returned '$xb'; client: $(journalctl -u xc --no-pager -n 2 2>/dev/null | tail -1)"; fi
  iptables -t nat -D OUTPUT -p tcp --dport 19098 -m owner ! --uid-owner xistance -j REDIRECT --to-port $XRAY_PORT 2>/dev/null
fi

# --------------------------------------------------------------- reconnect ----
# Per-method SIGKILL recovery, for the systemd-supervised units the panel writes.
#
# The GOST proof in TASK-123 used this shape, and every step matters:
#   1. probe succeeds            -> the tunnel really carried bytes
#   2. SIGKILL the MainPID       -> not a graceful stop
#   3. probe now FAILS           -> proves the tunnel actually died, so a later
#                                   success cannot be the old process still serving
#   4. systemd restarts it       -> new MainPID, Restart=on-failure
#   5. the SAME probe succeeds   -> no operator action, real recovery
# Step 3 is the one that is easy to omit and the one that makes the rest meaningful.
reconnect_case() {
  local name="$1" unit="$2" port="$3"
  local before after downpid newpid
  before=$(body "$port")
  if [ "$before" != "HELLO-XR" ]; then
    bad "$name reconnect: carried bytes before the kill" "port $port returned '$before'"
    return
  fi
  downpid=$(systemctl show -p MainPID --value "$unit" 2>/dev/null)
  kill -9 "$downpid" 2>/dev/null
  echo "  SIGKILLed $name pid=$downpid"
  # Prove it is DOWN, so a later success is recovery rather than the old process.
  sleep 2
  after=$(body "$port")
  if [ "$after" = "HELLO-XR" ]; then
    bad "$name reconnect: the tunnel was really killed" "port $port still served HELLO-XR after kill -9 $downpid"
    return
  fi
  ok "$name reconnect: the tunnel is DOWN after SIGKILL (no false recovery)"
  for i in $(seq 1 20); do
    sleep 1
    newpid=$(systemctl show -p MainPID --value "$unit" 2>/dev/null)
    if [ -n "$newpid" ] && [ "$newpid" != "0" ] && [ "$newpid" != "$downpid" ] && \
       [ "$(body "$port")" = "HELLO-XR" ]; then
      ok "$name reconnect: systemd recovered it (pid $downpid -> $newpid) and the same probe succeeds"
      return
    fi
  done
  bad "$name reconnect: systemd recovered it" "still pid=$(systemctl show -p MainPID --value "$unit" 2>/dev/null) after 20s, body='$(body "$port")'"
}

echo "  --- per-method reconnect (SIGKILL + systemd Restart=on-failure) ---"
reconnect_case FRP frpc 18100
reconnect_case BACKHAUL bhc 18101
reconnect_case DIRECT gost-direct 18103
# XRAY needs its REDIRECT back in place for the probe, and scoped so the tunnel's own
# outbound is not captured -- the same shape the traffic case used.
if [ -f /etc/systemd/system/xc.service ]; then
  iptables -t nat -A OUTPUT -p tcp --dport 19098 -m owner ! --uid-owner xistance -j REDIRECT --to-port $XRAY_PORT 2>/dev/null
  reconnect_case XRAY xc 19098
  iptables -t nat -D OUTPUT -p tcp --dport 19098 -m owner ! --uid-owner xistance -j REDIRECT --to-port $XRAY_PORT 2>/dev/null
fi

# ---------------------------------------------------------------- cleanup ----
systemctl stop frps frpc bhs bhc ot gost-direct xs xc 2>/dev/null
rm -f /etc/systemd/system/{ot,frps,frpc,bhs,bhc,gost-direct,xs,xc}.service
systemctl daemon-reload
echo "RESULT: pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
