import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
  scryptSync,
  timingSafeEqual,
} from "node:crypto";

// ---------------------------------------------------------------------------
// Encryption at rest (AES-256-GCM) — every secret stored in the database or on
// disk is wrapped with this. Master key comes from XTENC_KEY (hex) generated by
// install.sh. In production a missing key is a hard error.
// ---------------------------------------------------------------------------

const ENC_ALGO = "aes-256-gcm";
const KEY_LEN = 32;
const IV_LEN = 12;
const DEV_FALLBACK = "xistance-dev-key-do-not-use-in-production";

function masterKey(): Buffer {
  const raw = process.env.XTENC_KEY;
  if (raw) {
    const hex = Buffer.from(raw, "hex");
    if (hex.length === KEY_LEN) return hex;
    return scryptSync(raw, "xistance-panel-salt", KEY_LEN);
  }
  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "XTENC_KEY is not set. Generate one with `openssl rand -hex 32`.",
    );
  }
  return scryptSync(DEV_FALLBACK, "xistance-dev-salt", KEY_LEN);
}

/** Encrypt a plaintext string. Output format: `iv:tag:ciphertext` (base64). */
export function encryptSecret(plain: string): string {
  const key = masterKey();
  const iv = randomBytes(IV_LEN);
  const cipher = createCipheriv(ENC_ALGO, key, iv);
  const ct = Buffer.concat([cipher.update(plain, "utf8"), cipher.final()]);
  return [
    iv.toString("base64"),
    cipher.getAuthTag().toString("base64"),
    ct.toString("base64"),
  ].join(":");
}

export function decryptSecret(token: string): string {
  const [ivB64, tagB64, ctB64] = token.split(":");
  if (!ivB64 || !tagB64 || !ctB64) {
    throw new Error("Malformed encrypted secret");
  }
  const key = masterKey();
  const decipher = createDecipheriv(
    ENC_ALGO,
    key,
    Buffer.from(ivB64, "base64"),
  );
  decipher.setAuthTag(Buffer.from(tagB64, "base64"));
  const pt = Buffer.concat([
    decipher.update(Buffer.from(ctB64, "base64")),
    decipher.final(),
  ]);
  return pt.toString("utf8");
}

// ---------------------------------------------------------------------------
// Password hashing (scrypt, Node built-in — no native deps on restricted VPSes)
// ---------------------------------------------------------------------------

const SCRYPT_N = 16384;
const SCRYPT_R = 8;
const SCRYPT_P = 1;

/** Format: `scrypt:N:r:p:saltBase64:hashBase64` */
export function hashPassword(password: string): string {
  const salt = randomBytes(16);
  const hash = scryptSync(password, salt, 64, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
  });
  return `scrypt:${SCRYPT_N}:${SCRYPT_R}:${SCRYPT_P}:${salt.toString("base64")}:${hash.toString("base64")}`;
}

export function verifyPassword(password: string, stored: string): boolean {
  const [algo, nStr, rStr, pStr, saltB64, hashB64] = stored.split(":");
  if (algo !== "scrypt" || !saltB64 || !hashB64) return false;
  const salt = Buffer.from(saltB64, "base64");
  const expected = Buffer.from(hashB64, "base64");
  const actual = scryptSync(password, salt, expected.length, {
    N: Number(nStr),
    r: Number(rStr),
    p: Number(pStr),
  });
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

// ---------------------------------------------------------------------------
// Token / secret generators
// ---------------------------------------------------------------------------

export function randomBytesHex(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

/** URL-safe random token, e.g. for JWT secrets / API keys. */
export function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString("base64url");
}

/** Human-friendly password with safe alphabet, e.g. admin bootstrap. */
export function randomPassword(length = 16): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%";
  let out = "";
  const bytes = randomBytes(length);
  for (let i = 0; i < length; i++) out += alphabet[bytes[i] % alphabet.length];
  return out;
}
